### ISSUE TITLE
BUG: 当文件夹无写入权限，会修改图标失败

### ISSUE THREAD

**Issue by pinkyrie** [MrBeanCpp/Dr-Folder#1]
- SHGetSetFolderCustomSettings米有返回失败代码，且居然接收左斜杠path
- 需要检测到失败并要求提权

-- by cls & darli

**Comment by MrBeanCpp** [comment]
commit 0deb120b946aac713594784b4b366697508af8c5
不可写的话弹窗提示用户以管理员身份重新运行；进程貌似无法再运行中提权
